services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    networks:
      - db_network
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=chinookdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./2.chinook_pg_serial_pk_proper_naming.sql:/docker-entrypoint-initdb.d/initdb.sql  
    healthcheck:
      test: ["CMD", "pg_isready", "-p", "5432", "-U", "postgres"]
      interval: 60s
      timeout: 20s
      retries: 5
   
  cloudbeaver:
    image: dbeaver/cloudbeaver:latest  
    container_name: cloudbeaver
    restart: always
    ports:
      - 8978:8978
    depends_on:
      - postgres  
    networks:
      - db_network
    volumes:
      - cloudbeaver_data:/opt/cloudbeaver
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8978"]
      interval: 30s  
      timeout: 10s   
      retries: 5    

networks:
  db_network:
    driver: bridge

volumes:
  postgres_data:
  cloudbeaver_data:

